version: "3.7"

services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        container_name: mysql-container-auth
        # build: ./api/db
        environment: 
            MYSQL_DATABASE: auth
            MYSQL_ROOT_PASSWORD: 1234
        volumes:
            - ./src/database/dbdocker:/var/lib/mysql
        restart: always

    app:
        image: node:alpine
        command: npm start
        ports: 
            - "9001:9001"
        volumes: 
            - ./api:/usr/app
        container_name: node-container
        restart: always
        depends_on: 
            - db